import { serve } from '@hono/node-server';
import { openDatabase } from './db/index.js';
import { Repo } from './db/repo.js';
import { FanRepo } from './db/fans.js';
import { AgencyService } from './services/agency.js';
import { FanService } from './services/fans.js';
import { RecruitmentService } from './services/recruitment.js';
import { RecruitmentRepo } from './db/recruitment.js';
import { createApp } from './web/server.js';
import { creatorConfig } from './creators/index.js';
const mk = (port: number, cr: string, names: string[], extra: object) => {
  const db = openDatabase(':memory:');
  const repo = new Repo(db);
  for (const n of names) repo.upsertClient({ name: n, rule: { ratePer1kCents: 0, minViews: 0, capCents: null } });
  const agency = new AgencyService(repo);
  const fans = new FanService(repo, new FanRepo(db), agency, `http://localhost:${port}`, undefined, creatorConfig(cr));
  fans.bootstrap();
  if (cr === 'beone') fans.saveSettings?.({ clientId: repo.listClients()[0]!.id } as any);
  serve({ fetch: createApp({ repo, agency, fans, recruitment: new RecruitmentService(repo, new RecruitmentRepo(repo.db), agency), bot: {}, password: 'pw', ...extra } as any).fetch, port });
};
mk(4101, 'squiduu', [], {});
mk(4100, 'beone', ['BeOne', 'Loann'], { marsSites: [{ name: 'BeOne', url: 'http://localhost:4100' }, { name: 'SQUIDUU', url: 'http://localhost:4101' }], selfUrl: 'http://localhost:4100' });
