import type { CreatorConfig } from './types.js';

/** BeOnePourcent : site coloré (gabarit « playful »), récompenses livrées dans son jeu Roblox. */
export const beone: CreatorConfig = {
  id: 'beone',
  programName: 'BEONE REWARDS',
  creatorName: 'BeOnePourcent',
  youtube: 'BeOnePourcent',
  robloxUsername: 'BeOnePourcentt',
  theme: 'playful',
  colors: { bg: '#FAFAF7', card: '#FFFFFF', border: '#EAE8DF', text: '#111111', muted: '#6E6C66', accent: '#FFD83D', accentInk: '#111111' },
  pointsPer1000: 10,
  rewardAccount: {
    kind: 'roblox',
    title: 'Compte Roblox',
    label: 'Pseudo Roblox (pour recevoir tes récompenses)',
    placeholder: 'TonPseudoRoblox',
    badge: 'Roblox relié',
    deliveryHint: 'Tu la reçois dans le jeu à ta prochaine connexion.',
  },
  reward: null,
  levels: [
    { name: 'Débutant', emoji: '🌱', min: 0 },
    { name: 'Clippeur', emoji: '⚡', min: 10_000 },
    { name: 'Pro', emoji: '🔥', min: 100_000 },
    { name: '1%', emoji: '👑', min: 1_000_000 },
  ],
  discord: {
    welcome: [
      '👋 **Salut et bienvenue sur BeOne Clipping !**',
      '',
      'Ici, tu peux gagner **gratuitement des gamepass Roblox** grâce à tes clips de {creator} 🎮',
      '',
      '🎁 **Comment gagner des récompenses ?**',
      'C’est très simple : tu fais des clips des vidéos de {creator} 👀',
      '',
      '📱 Crée tes propres comptes **YouTube, TikTok et Instagram**, puis poste tes clips dessus.',
      '✨ Les vues de YouTube + TikTok + Instagram sont **toutes comptées ensemble** !',
      '🪙 **1 000 vues = {rate} coins**, à échanger contre des **gamepass livrés direct dans le jeu**.',
      '',
      '😕 **Tu ne sais pas faire de montage ?**',
      'Pas de panique, c’est normal quand on débute 😊 Pose tes questions dans ❓│aide : on t’explique tout, étape par étape.',
      '',
      '🚀 **Prêt à commencer l’aventure ?**',
      'Clique sur **➡️ Continuer** juste en dessous pour découvrir les règles et le déroulement 👇',
    ].join('\n'),
    rules: [
      '🎮 Bienvenue sur le serveur officiel de clipping de {creator} !',
      'Le but est simple : créer des clips de ses vidéos et les poster sur tes comptes. 🎥',
      'Merci de respecter ces quelques règles pour garder un serveur propre et agréable 👇',
      '',
      '**1️⃣・Respect** 🤝',
      'Respecte les autres membres. ❌ Pas d’insultes, de moqueries ou de harcèlement. 🗣️ Les désaccords se règlent calmement.',
      '',
      '**2️⃣・Clips** 🎥',
      '✂️ Les clips doivent venir des vidéos de {creator}. 🔥 Les moments drôles, impressionnants ou insolites sont les bienvenus !',
      '',
      '**3️⃣・Pas de triche** 🚫',
      '❌ Pas de faux clips, de faux comptes ni de vues achetées. ⚠️ Les coins gagnés en trichant sont retirés.',
      '',
      '**4️⃣・Un compte = une personne** 🔗',
      'Un compte TikTok, YouTube ou Instagram ne peut être relié qu’à un seul clippeur.',
      '',
      '**5️⃣・Pas de spam ni de pub** 📢',
      '🚫 Pas de messages en boucle ni de mentions inutiles. ❌ Pas de pub pour d’autres serveurs, chaînes ou comptes sans l’accord du staff.',
      '',
      '**6️⃣・Sécurité** 🛡️',
      '🔒 Ne partage jamais tes infos perso (📍 adresse, 📱 numéro, 🔑 mot de passe, 🏫 école) et ne les demande pas aux autres.',
      '',
      '**7️⃣・Staff** 👮',
      '🛡️ Respecte les décisions du staff. 📩 Un problème ? Écris dans ❓│aide plutôt que de lancer une dispute.',
      '',
      '━━━━━━━━━━━━━━━━━━',
      '🎬 **Objectif : faire découvrir {creator} au plus de monde possible !**',
      '✂️ CLIP • POSTE • GAGNE 🪙',
      '',
      '⚠️ Le non-respect des règles peut entraîner un avertissement, un mute ou un bannissement.',
    ].join('\n'),
  },
  statuses: { pending: 'En route vers le jeu 🚚', delivered: 'Reçu en jeu ✅', refunded: 'Remboursé' },
  texts: {
    heroTitle: 'Fais des vues. Gagne des Coins.',
    heroText: 'Clippe BeOnePourcent, fais exploser les vues et échange tes Coins contre des récompenses Roblox.',
    heroCta: 'Commencer à clipper',
    steps: [
      { title: 'Je clippe', text: 'Un moment de BeOne' },
      { title: 'Je fais des vues', text: 'TikTok, Insta, YouTube' },
      { title: 'Je gagne des coins', text: '10 coins / 1 000 vues' },
      { title: "J'achète des gamepass", text: 'Livrés dans le jeu' },
    ],
    shopTitle: 'Récompenses',
    shopText: 'Échange tes coins contre des gamepass et objets Roblox, livrés direct dans le jeu.',
    clipTitle: 'Clippe & gagne',
    clipText: 'Poste des clips de BeOnePourcent sur TikTok, Insta ou YouTube. On suit tes vues, chaque vue te rapporte des coins.',
    rankingText: 'Les clippeurs qui ont fait le plus de vues cette semaine.',
    footer: 'BeOne Rewards · BeOnePourcent',
    deliveredDm: '✅ Ton **{item}** est arrivé dans le jeu !',
    dmFooter: 'BeOne Rewards · 🪙 Fais des vues, gagne des coins',
  },
};
