import type { CreatorConfig } from './types.js';

/**
 * Cubi Game (Roblox) : même mise en page riche que Loann (style « ms »), à sa charte noir / blanc / orange (skin « cubi »).
 * Récompense : 1 mois de Roblox Academy pour 100 k vues, livré sur l'e-mail du clippeur.
 */
export const cubi: CreatorConfig = {
  id: 'cubi',
  programName: 'CUBI GAME CLIPPING',
  creatorName: 'Cubi Game',
  clipKeywords: ['Cubi', 'CubiGame', 'Cubi Game'],
  // À compléter : handle(s) de la chaîne YouTube (photo HD, vidéos du créateur)
  youtube: '',
  theme: 'pop',
  style: 'ms',
  images: { reward: 'cubi-academy.webp' },
  // Noir & blanc du cube + orange du logo Roblox Academy
  colors: { bg: '#FFFFFF', card: '#FFFFFF', border: '#111111', text: '#111111', muted: '#555555', accent: '#FF9A1F', accentInk: '#111111', accent2: '#FFB547', accent3: '#333333', highlight: '#FF9A1F' },
  font: 'Space Grotesk',
  logoText: 'CUBI GAME',
  pointsPer1000: 10,
  rewardAccount: {
    kind: 'email',
    title: 'Accès Roblox Academy',
    label: 'E-mail pour ton accès Roblox Academy',
    placeholder: 'ton@email.com',
    badge: 'Accès relié',
    deliveryHint: 'Ton accès Roblox Academy est envoyé sur cet e-mail.',
  },
  reward: {
    name: '1 mois de Roblox Academy',
    description: 'Apprends à créer et faire grandir ton propre jeu Roblox avec Cubi Game. Les mois s’additionnent.',
    price: 1_000,
    ref: 'academy-1m',
    url: '#',
    linkLabel: 'Découvrir la Roblox Academy',
  },
  gradeWindowDays: 30,
  levels: [
    { name: 'Débutant', emoji: '🌱', min: 0 },
    { name: 'Confirmé', emoji: '⚡', min: 10_000 },
    { name: 'Pro', emoji: '🔥', min: 100_000 },
    { name: 'Élite', emoji: '💎', min: 1_000_000 },
  ],
  ms: {
    skin: 'cubi',
    heroLine: 'tes vues te paient la formation pour créer ton jeu Roblox',
    statLeft: { badge: '🎮', text: 'Apprends à créer ton propre jeu Roblox' },
    statRight: { big: '10', text: 'coins pour 1 000 vues' },
    ctaNote: 'Connecte-toi avec Discord pour voir où tu en es',
    offer: { title: 'Les mois de Roblox Academy s’additionnent', text: '1 000 coins = 1 mois de Roblox Academy, sans limite !', side: 'La formation de Cubi Game' },
    timelineTitle: 'Clipper Cubi Game c’est',
    timeline: [
      { emoji: '✂️', title: 'Des clips', text: 'Tu choisis un passage de Cubi Game qui mérite d’être vu, et tu le montes à ta façon.' },
      { emoji: '📱', title: 'Tes comptes', text: 'Tu postes sur TikTok, Instagram ou YouTube Shorts. Toutes tes vues sont additionnées.' },
      { emoji: '🪙', title: 'Des coins', text: '10 coins pour 1 000 vues, comptés chaque nuit, automatiquement.' },
      { emoji: '🏆', title: 'Un classement', text: 'Chaque semaine, le top 3 des clippeurs est mis en avant sur le Discord.' },
      { emoji: '🧱', title: 'La Roblox Academy', text: 'Tu échanges tes coins contre des mois de formation pour créer ton jeu Roblox.' },
    ],
    tiersTitle: 'Et toi, quel clippeur deviendras-tu ?',
    band: '100 K VUES = 1 MOIS DE ROBLOX ACADEMY',
    alone: { title: 'Seul', text: 'Des clips postés pour rien : pas de récompense, pas de suivi, personne pour t’aider…' },
    withUs: { title: 'Avec Cubi Game', lines: ['Tes vues paient.', 'Des mois de Roblox Academy offerts', 'Un classement chaque semaine', 'Un Discord pour t’aider', 'Une commu de clippeurs'] },
    faqAside: 'Tu as encore des questions ? Pose-les sur le Discord !',
  },
  statuses: { pending: 'En attente', delivered: 'Livré ✅', refunded: 'Remboursé' },
  texts: {
    heroTitle: '**100 k vues** = 1 mois de Roblox Academy',
    heroText: 'Poste des clips de Cubi Game sur TikTok, Instagram ou YouTube. Chaque vue te rapporte des coins, que tu échanges contre des mois de Roblox Academy.',
    heroCta: 'Voir ma progression',
    steps: [
      { title: 'Crée ton clip', text: 'Un passage de Cubi Game qui mérite d’être vu.' },
      { title: 'Poste-le', text: 'Sur TikTok, Instagram ou YouTube.' },
      { title: 'Gagne des coins', text: '10 coins pour 1 000 vues, tous comptes confondus.' },
      { title: 'Prends ton mois', text: '1 000 coins = 1 mois de Roblox Academy.' },
    ],
    shopTitle: 'Récompenses',
    shopText: 'Échange tes coins contre des mois de Roblox Academy, la formation de Cubi Game.',
    clipTitle: 'Clipper',
    clipText: 'Poste des clips de Cubi Game sur TikTok, Instagram ou YouTube. Tes vues sont comptées toutes les 1 à 2 nuits.',
    rankingText: 'Les clippeurs qui ont fait le plus de vues ces 7 derniers jours.',
    footer: 'Cubi Game Clipping',
    deliveredDm: '✅ Ton **{item}** a été ajouté sur ton compte !',
    dmFooter: 'Cubi Game Clipping · Clippe, gagne la Roblox Academy',
    faq: [
      { q: 'Comment je gagne des coins ?', a: 'Tu postes des clips de Cubi Game sur TikTok, Instagram ou YouTube. Chaque vue compte : 1 000 vues = 10 coins, tous comptes confondus.' },
      { q: 'Comment je relie mes comptes ?', a: 'Sur le Discord, clique sur « S’inscrire » dans le salon inscription et renseigne tes comptes.' },
      { q: 'Quand mes vues sont-elles comptées ?', a: 'Une fois par jour. Seules les vues faites après ton inscription rapportent des coins.' },
      { q: 'Comment je reçois mon mois de Roblox Academy ?', a: 'Renseigne ton e-mail dans ton profil et échange 1 000 coins dans la boutique : ton accès est envoyé sur cet e-mail et tu reçois un message Discord dès que c’est fait.' },
      { q: 'Il faut combien d’abonnés ?', a: 'Aucun minimum. Un compte qui vient de démarrer peut gagner des coins dès son premier clip.' },
    ],
    finalTitle: 'Prêt à **clipper** ?',
    finalText: 'Connecte-toi avec Discord, relie tes comptes et commence à gagner des coins dès ton prochain clip.',
  },
};
