import type { CreatorConfig } from './types.js';

/**
 * DEBO PLAYS (youtube.com/@DEBO-PLAYS) : gabarit « pop » (public jeune : multicolore, énergique, fluide).
 * Récompense : des Robux, envoyés par le staff sur le compte Roblox du clippeur.
 */
export const debo: CreatorConfig = {
  id: 'debo',
  programName: 'DEBO PLAYS',
  creatorName: 'DEBO',
  clipKeywords: ['DEBO', 'DeboPlays'],
  youtube: 'DEBO-PLAYS',
  theme: 'pop',
  colors: { bg: '#0D0A24', card: '#1A1540', border: '#2E2762', text: '#FFFFFF', muted: '#B9B2E6', accent: '#FF3EA5', accentInk: '#FFFFFF', accent2: '#FFD60A', accent3: '#29E7FF' },
  font: 'Nunito',
  logoText: 'debo.',
  pointsPer1000: 10,
  rewardAccount: {
    kind: 'roblox',
    title: 'Compte Roblox',
    label: 'Pseudo Roblox (pour recevoir tes Robux)',
    placeholder: 'TonPseudoRoblox',
    badge: 'Roblox relié',
    deliveryHint: 'Tes Robux sont envoyés sur ce compte Roblox par le staff.',
  },
  // 100 000 vues = 50 Robux (1 M vues = 500 Robux). Les autres paliers (250, 500 Robux) s'ajoutent depuis Mars
  reward: {
    name: '50 Robux',
    description: '50 Robux envoyés sur ton compte Roblox. Échange autant de fois que tu veux.',
    price: 1000,
    ref: 'robux-100',
    url: 'https://www.roblox.com/',
    linkLabel: 'Roblox',
  },
  levels: [
    { name: 'Débutant', emoji: '🌱', min: 0 },
    { name: 'Confirmé', emoji: '⚡', min: 10_000 },
    { name: 'Pro', emoji: '🔥', min: 100_000 },
    { name: 'Élite', emoji: '💎', min: 1_000_000 },
  ],
  discord: {
    welcome: [
      '👋 **Salut et bienvenue sur DEBO Clipping !**',
      '',
      'Ici, tu peux gagner **des Robux gratuitement** grâce à tes clips de {creator} 🎮',
      '',
      '🎁 **Comment gagner des récompenses ?**',
      'C’est très simple : tu fais des clips des vidéos de {creator} 👀',
      '',
      '📱 Crée tes propres comptes **YouTube, TikTok et Instagram**, puis poste tes clips dessus.',
      '✨ Les vues de YouTube + TikTok + Instagram sont **toutes comptées ensemble** !',
      '🪙 **1 000 vues = {rate} coins**, et **100 000 vues = 50 Robux** (1 M de vues = 500 Robux).',
      '',
      '😕 **Tu ne sais pas faire de montage ?**',
      'Pas de panique, c’est normal quand on débute 😊 Pose tes questions dans ❓│aide : on t’explique tout, étape par étape.',
      '',
      '🚀 **Prêt à commencer l’aventure ?**',
      'Clique sur **➡️ Continuer** juste en dessous pour découvrir les règles et le déroulement 👇',
    ].join('\n'),
    rules: [
      '🎮 Bienvenue sur le serveur officiel de clipping de {creator} !',
      'Le but est simple : créer des clips de ses vidéos et les poster sur tes comptes. 🎥',
      'Merci de respecter ces quelques règles pour garder un serveur propre et agréable 👇',
      '',
      '**1️⃣・Respect** 🤝',
      'Respecte les autres membres. ❌ Pas d’insultes, de moqueries ou de harcèlement. 🗣️ Les désaccords se règlent calmement.',
      '',
      '**2️⃣・Clips** 🎥',
      '✂️ Les clips doivent venir des vidéos de {creator}. 🔥 Les moments drôles, impressionnants ou insolites sont les bienvenus !',
      '',
      '**3️⃣・Pas de triche** 🚫',
      '❌ Pas de faux clips, de faux comptes ni de vues achetées. ⚠️ Les coins gagnés en trichant sont retirés.',
      '',
      '**4️⃣・Un compte = une personne** 🔗',
      'Un compte TikTok, YouTube ou Instagram ne peut être relié qu’à un seul clippeur.',
      '',
      '**5️⃣・Pas de spam ni de pub** 📢',
      '🚫 Pas de messages en boucle ni de mentions inutiles. ❌ Pas de pub pour d’autres serveurs, chaînes ou comptes sans l’accord du staff.',
      '',
      '**6️⃣・Sécurité** 🛡️',
      '🔒 Ne partage jamais tes infos perso (📍 adresse, 📱 numéro, 🔑 mot de passe, 🏫 école) et ne les demande pas aux autres.',
      '',
      '**7️⃣・Staff** 👮',
      '🛡️ Respecte les décisions du staff. 📩 Un problème ? Écris dans ❓│aide plutôt que de lancer une dispute.',
      '',
      '━━━━━━━━━━━━━━━━━━',
      '🎬 **Objectif : faire découvrir {creator} au plus de monde possible !**',
      '✂️ CLIP • POSTE • GAGNE 🪙',
      '',
      '⚠️ Le non-respect des règles peut entraîner un avertissement, un mute ou un bannissement.',
    ].join('\n'),
  },
  statuses: { pending: 'Robux en route 🚚', delivered: 'Robux reçus ✅', refunded: 'Remboursé' },
  texts: {
    heroTitle: 'Clippe DEBO. **Gagne des Robux.**',
    heroText: 'Poste des clips de DEBO sur TikTok, Instagram ou YouTube. Chaque vue te rapporte des coins, que tu échanges contre des Robux.',
    heroCta: 'Commencer à clipper',
    steps: [
      { title: 'Crée ton clip', text: 'Un passage de DEBO qui mérite d’être vu.' },
      { title: 'Poste-le', text: 'Sur TikTok, Instagram ou YouTube.' },
      { title: 'Gagne des coins', text: '10 coins pour 1 000 vues, tous comptes confondus.' },
      { title: 'Prends tes Robux', text: 'Échange tes coins dans la boutique, on t’envoie les Robux.' },
    ],
    shopTitle: 'Récompenses',
    shopText: 'Échange tes coins contre des Robux, envoyés sur ton compte Roblox.',
    clipTitle: 'Clipper',
    clipText: 'Poste des clips de DEBO sur TikTok, Instagram ou YouTube. Tes vues sont comptées une fois par jour.',
    rankingText: 'Les clippeurs qui ont fait le plus de vues ces 7 derniers jours.',
    footer: 'DEBO PLAYS',
    deliveredDm: '✅ Tes **{item}** ont été envoyés sur ton compte Roblox !',
    dmFooter: 'DEBO PLAYS · Clippe, gagne des Robux',
    faq: [
      { q: 'Comment je gagne des coins ?', a: 'Tu postes des clips de DEBO sur TikTok, Instagram ou YouTube. Chaque vue compte : 1 000 vues = 10 coins, tous comptes confondus.' },
      { q: 'Comment je relie mes comptes ?', a: 'Sur le Discord, clique sur « S’inscrire » dans le salon inscription et renseigne tes comptes.' },
      { q: 'Quand mes vues sont-elles comptées ?', a: 'Une fois par jour. Seules les vues faites après ton inscription rapportent des coins.' },
      { q: 'Comment je reçois mes Robux ?', a: 'Relie ton pseudo Roblox dans ton profil, échange tes coins dans la boutique : le staff t’envoie les Robux sur ce compte et tu reçois un message Discord dès que c’est fait.' },
      { q: 'Il faut combien d’abonnés ?', a: 'Aucun minimum. Un compte qui vient de démarrer peut gagner des coins dès son premier clip.' },
    ],
    finalTitle: 'Prêt à **clipper** ?',
    finalText: 'Connecte-toi avec Discord, relie tes comptes et commence à gagner des coins dès ton prochain clip.',
  },
};
