import type { CreatorConfig } from './types.js';

/**
 * Loann (youtube.com/@LoannLV + @netabonnepas-el2vd) : gabarit « pop » variante « sticker » (memes, couleurs de sa bannière).
 * Récompense : 1 mois de MS pour 1 M de vues, livré sur l'e-mail du clippeur.
 */
export const loann: CreatorConfig = {
  id: 'loann',
  programName: 'LOANN CLIPPING',
  creatorName: 'Loann',
  youtube: 'LoannLV,netabonnepas-el2vd',
  theme: 'pop',
  // Palette tirée de sa bannière (coucher de soleil peint) et du logo MS (gemmes rouge-orange, étoile jaune)
  style: 'sticker',
  images: { banner: 'loann-banner.webp', reward: 'loann-reward.webp' },
  colors: { bg: '#150B2B', card: '#22143F', border: '#3A2766', text: '#FFFFFF', muted: '#C9BCEB', accent: '#FF3D5E', accentInk: '#FFFFFF', accent2: '#FFC21A', accent3: '#7B4DFF' },
  font: 'Baloo 2',
  logoText: 'loann.',
  pointsPer1000: 10,
  rewardAccount: {
    kind: 'email',
    title: 'Compte MS',
    label: 'E-mail de ton compte MS',
    placeholder: 'ton@email.com',
    badge: 'Compte MS relié',
    deliveryHint: 'Le mois est ajouté au compte MS lié à cet e-mail.',
  },
  reward: {
    name: '1 mois de MS',
    description: 'Un mois de MS offert. Échange autant de fois que tu veux : les mois s’additionnent.',
    price: 10000,
    ref: 'ms-1m',
    url: 'https://www.youtube.com/@LoannLV',
    linkLabel: 'La chaîne de Loann',
  },
  levels: [
    { name: 'Débutant', emoji: '🌱', min: 0 },
    { name: 'Confirmé', emoji: '⚡', min: 10_000 },
    { name: 'Pro', emoji: '🔥', min: 100_000 },
    { name: 'Élite', emoji: '💎', min: 1_000_000 },
  ],
  discord: {
    welcome: [
      '👋 **Salut et bienvenue sur Loann Clipping !**',
      '',
      'Ici, tu peux gagner **des mois de MS gratuitement** grâce à tes clips de {creator} 🔥',
      '',
      '🎁 **Comment gagner des récompenses ?**',
      'C’est très simple : tu fais des clips des vidéos de {creator} 👀',
      '',
      '📱 Crée tes propres comptes **YouTube, TikTok et Instagram**, puis poste tes clips dessus.',
      '✨ Les vues de YouTube + TikTok + Instagram sont **toutes comptées ensemble** !',
      '🪙 **1 000 vues = {rate} coins**, et **10 000 coins = 1 mois de MS**.',
      '',
      '😕 **Tu ne sais pas faire de montage ?**',
      'Pas de panique, c’est normal quand on débute 😊 Pose tes questions dans ❓│aide : on t’explique tout, étape par étape.',
      '',
      '🚀 **Prêt à commencer l’aventure ?**',
      'Clique sur **➡️ Continuer** juste en dessous pour découvrir les règles et le déroulement 👇',
    ].join('\n'),
    rules: [
      '🎮 Bienvenue sur le serveur officiel de clipping de {creator} !',
      'Le but est simple : créer des clips de ses vidéos et les poster sur tes comptes. 🎥',
      'Merci de respecter ces quelques règles pour garder un serveur propre et agréable 👇',
      '',
      '**1️⃣・Respect** 🤝',
      'Respecte les autres membres. ❌ Pas d’insultes, de moqueries ou de harcèlement. 🗣️ Les désaccords se règlent calmement.',
      '',
      '**2️⃣・Clips** 🎥',
      '✂️ Les clips doivent venir des vidéos de {creator}. 🔥 Les moments drôles, impressionnants ou insolites sont les bienvenus !',
      '',
      '**3️⃣・Pas de triche** 🚫',
      '❌ Pas de faux clips, de faux comptes ni de vues achetées. ⚠️ Les coins gagnés en trichant sont retirés.',
      '',
      '**4️⃣・Un compte = une personne** 🔗',
      'Un compte TikTok, YouTube ou Instagram ne peut être relié qu’à un seul clippeur.',
      '',
      '**5️⃣・Pas de spam ni de pub** 📢',
      '🚫 Pas de messages en boucle ni de mentions inutiles. ❌ Pas de pub pour d’autres serveurs, chaînes ou comptes sans l’accord du staff.',
      '',
      '**6️⃣・Sécurité** 🛡️',
      '🔒 Ne partage jamais tes infos perso (📍 adresse, 📱 numéro, 🔑 mot de passe, 🏫 école) et ne les demande pas aux autres.',
      '',
      '**7️⃣・Staff** 👮',
      '🛡️ Respecte les décisions du staff. 📩 Un problème ? Écris dans ❓│aide plutôt que de lancer une dispute.',
      '',
      '━━━━━━━━━━━━━━━━━━',
      '🎬 **Objectif : faire découvrir {creator} au plus de monde possible !**',
      '✂️ CLIP • POSTE • GAGNE 🪙',
      '',
      '⚠️ Le non-respect des règles peut entraîner un avertissement, un mute ou un bannissement.',
    ].join('\n'),
  },
  statuses: { pending: 'En attente', delivered: 'Livré ✅', refunded: 'Remboursé' },
  texts: {
    heroTitle: 'Clippe Loann. **Gagne des mois de MS.**',
    heroText: 'Poste des clips de Loann sur TikTok, Instagram ou YouTube. Chaque vue te rapporte des coins, que tu échanges contre des mois de MS.',
    heroCta: 'Commencer à clipper',
    steps: [
      { title: 'Crée ton clip', text: 'Un passage de Loann qui mérite d’être vu.' },
      { title: 'Poste-le', text: 'Sur TikTok, Instagram ou YouTube.' },
      { title: 'Gagne des coins', text: '10 coins pour 1 000 vues, tous comptes confondus.' },
      { title: 'Prends ton mois', text: '10 000 coins = 1 mois de MS, ajouté sur ton compte.' },
    ],
    shopTitle: 'Récompenses',
    shopText: 'Échange tes coins contre des mois de MS, ajoutés sur ton compte.',
    clipTitle: 'Clipper',
    clipText: 'Poste des clips de Loann sur TikTok, Instagram ou YouTube. Tes vues sont comptées une fois par jour.',
    rankingText: 'Les clippeurs qui ont fait le plus de vues ces 7 derniers jours.',
    footer: 'Loann Clipping',
    deliveredDm: '✅ Ton **{item}** a été ajouté sur ton compte !',
    dmFooter: 'Loann Clipping · Clippe, gagne des mois de MS',
    faq: [
      { q: 'Comment je gagne des coins ?', a: 'Tu postes des clips de Loann sur TikTok, Instagram ou YouTube. Chaque vue compte : 1 000 vues = 10 coins, tous comptes confondus.' },
      { q: 'Comment je relie mes comptes ?', a: 'Sur le Discord, clique sur « S’inscrire » dans le salon inscription et renseigne tes comptes.' },
      { q: 'Quand mes vues sont-elles comptées ?', a: 'Une fois par jour. Seules les vues faites après ton inscription rapportent des coins.' },
      { q: 'Comment je reçois mon mois de MS ?', a: 'Renseigne l’e-mail de ton compte MS dans ton profil, échange 10 000 coins dans la boutique : le mois est ajouté sur ce compte et tu reçois un message Discord dès que c’est fait.' },
      { q: 'Il faut combien d’abonnés ?', a: 'Aucun minimum. Un compte qui vient de démarrer peut gagner des coins dès son premier clip.' },
    ],
    finalTitle: 'Prêt à **clipper** ?',
    finalText: 'Connecte-toi avec Discord, relie tes comptes et commence à gagner des coins dès ton prochain clip.',
  },
};
