import type { CreatorConfig } from './types.js';

/**
 * Loann (youtube.com/@LoannLV + @netabonnepas-el2vd) : site au style « ms » (charte de Merguez Superstar, ms-creators.com).
 * Récompense : 1 mois de Merguez Superstar (sa formation YouTube) pour 1 M de vues, livré sur l'e-mail du clippeur.
 */
export const loann: CreatorConfig = {
  id: 'loann',
  programName: 'LOANN CLIPPING',
  creatorName: 'Loann',
  clipKeywords: ['Loann', 'LoannLV'],
  // Pas de #tag obligatoire, et tous les clips postés depuis le 1er août 2026 comptent (même avant l'inscription)
  clipRule: false,
  countViewsFrom: '2026-08-01',
  youtube: 'LoannLV,netabonnepas-el2vd',
  theme: 'pop',
  style: 'ms',
  images: { banner: 'loann-banner.webp', reward: 'loann-reward.webp' },
  // Charte de Merguez Superstar (ms-creators.com) : crème #FFF7E6, encre #212121, jaune #FFD36E, pêche / orange / corail
  colors: { bg: '#FFF7E6', card: '#FFFFFF', border: '#212121', text: '#212121', muted: '#5C4A39', accent: '#FF9F4A', accentInk: '#212121', accent2: '#FFD36E', accent3: '#FFA189', highlight: '#FF9F4A' },
  font: 'Inter',
  logoText: 'loann.',
  pointsPer1000: 10,
  rewardAccount: {
    kind: 'email',
    title: 'Accès Merguez Superstar',
    label: 'E-mail pour ton accès Merguez Superstar',
    placeholder: 'ton@email.com',
    badge: 'Accès relié',
    deliveryHint: 'Ton accès Merguez Superstar est envoyé sur cet e-mail.',
  },
  reward: {
    name: '1 mois de Merguez Superstar',
    description: 'La commu pour vivre de YouTube : +3 100 YouTubers accompagnés depuis 2023. Formation, coachings chaque semaine, Discord privé avec des YouTubers. Les mois s’additionnent.',
    price: 10000,
    ref: 'ms-1m',
    url: 'https://ms-creators.com/',
    linkLabel: 'Découvrir Merguez Superstar',
  },
  // Grades Discord du mois glissant : 100 k vues sur 30 jours = Pro ; s'il redescend sous 100 k le mois d'après → Confirmé
  gradeWindowDays: 30,
  levels: [
    { name: 'Débutant', emoji: '🌱', min: 0 },
    { name: 'Confirmé', emoji: '⚡', min: 10_000 },
    { name: 'Pro', emoji: '🔥', min: 100_000 },
    { name: 'Élite', emoji: '💎', min: 1_000_000 },
  ],
  discord: {
    welcome: [
      '👋 **Salut et bienvenue sur Loann Clipping !**',
      '',
      'Ici, tu peux gagner **des mois de **Merguez Superstar** gratuitement** grâce à tes clips de {creator} 🔥',
      '',
      '🎁 **Comment gagner des récompenses ?**',
      'C’est très simple : tu fais des clips des vidéos de {creator} 👀',
      '',
      '📱 Crée tes propres comptes **YouTube, TikTok et Instagram**, puis poste tes clips dessus.',
      '✨ Les vues de YouTube + TikTok + Instagram sont **toutes comptées ensemble** !',
      '🪙 **1 000 vues = {rate} coins**, et **10 000 coins = 1 mois de Merguez Superstar**.',
      '',
      '😕 **Tu ne sais pas faire de montage ?**',
      'Pas de panique, c’est normal quand on débute 😊 Pose tes questions dans ❓│aide : on t’explique tout, étape par étape.',
      '',
      '🚀 **Prêt à commencer l’aventure ?**',
      'Clique sur **➡️ Continuer** juste en dessous pour découvrir les règles et le déroulement 👇',
    ].join('\n'),
    rules: [
      '🎮 Bienvenue sur le serveur officiel de clipping de {creator} !',
      'Le but est simple : créer des clips de ses vidéos et les poster sur tes comptes. 🎥',
      'Merci de respecter ces quelques règles pour garder un serveur propre et agréable 👇',
      '',
      '**1️⃣・Respect** 🤝',
      'Respecte les autres membres. ❌ Pas d’insultes, de moqueries ou de harcèlement. 🗣️ Les désaccords se règlent calmement.',
      '',
      '**2️⃣・Clips** 🎥',
      '✂️ Les clips doivent venir des vidéos de {creator}. 🔥 Les moments drôles, impressionnants ou insolites sont les bienvenus !',
      '',
      '**3️⃣・Pas de triche** 🚫',
      '❌ Pas de faux clips, de faux comptes ni de vues achetées. ⚠️ Les coins gagnés en trichant sont retirés.',
      '',
      '**4️⃣・Un compte = une personne** 🔗',
      'Un compte TikTok, YouTube ou Instagram ne peut être relié qu’à un seul clippeur.',
      '',
      '**5️⃣・Pas de spam ni de pub** 📢',
      '🚫 Pas de messages en boucle ni de mentions inutiles. ❌ Pas de pub pour d’autres serveurs, chaînes ou comptes sans l’accord du staff.',
      '',
      '**6️⃣・Sécurité** 🛡️',
      '🔒 Ne partage jamais tes infos perso (📍 adresse, 📱 numéro, 🔑 mot de passe, 🏫 école) et ne les demande pas aux autres.',
      '',
      '**7️⃣・Staff** 👮',
      '🛡️ Respecte les décisions du staff. 📩 Un problème ? Écris dans ❓│aide plutôt que de lancer une dispute.',
      '',
      '━━━━━━━━━━━━━━━━━━',
      '🎬 **Objectif : faire découvrir {creator} au plus de monde possible !**',
      '✂️ CLIP • POSTE • GAGNE 🪙',
      '',
      '⚠️ Le non-respect des règles peut entraîner un avertissement, un mute ou un bannissement.',
    ].join('\n'),
  },
  // Accueil façon ms-creators.com (avis : captures des vrais avis Trustpilot de MS, avec lien vers Trustpilot)
  ms: {
    rewardShort: 'MS',
    heroLine: 'tes vues te paient la formation YouTube n°1',
    heroImage: 'ms-hero-loann.webp',
    statLeft: { badge: 'N°1', text: 'Communauté formatrice de YouTube en France' },
    statRight: { big: '4.8/5', text: '97 avis sur Trustpilot' },
    ctaNote: 'Connecte-toi avec Discord pour voir où tu en es',
    offer: { title: 'Les mois de MS s’additionnent', text: '10 000 coins = 1 mois de Merguez Superstar, sans limite !', side: 'Rejoins la commu MS' },
    timelineTitle: 'Clipper Loann c’est',
    timeline: [
      { emoji: '✂️', title: 'Des clips', text: 'Tu choisis un passage de Loann qui mérite d’être vu, et tu le montes à ta façon.' },
      { emoji: '📱', title: 'Tes comptes', text: 'Tu postes sur TikTok, Instagram ou YouTube Shorts. Toutes tes vues sont additionnées.' },
      { emoji: '🪙', title: 'Des coins', text: '10 coins pour 1 000 vues, comptés chaque nuit, automatiquement.' },
      { emoji: '🏆', title: 'Un classement', text: 'Chaque semaine, le top 3 des clippeurs est mis en avant sur le Discord.' },
      { emoji: '🎁', title: 'Des mois de MS', text: 'Tu échanges tes coins contre Merguez Superstar, la commu pour vivre de YouTube.' },
    ],
    reviews: {
      url: 'https://fr.trustpilot.com/review/ms-creators.com',
      score: '97 avis — 4.8/5',
      top: [
        { name: 'Maxime j', meta: 'FR · 1 avis', title: 'MS est très correct', avatar: 'ms-av-maxime.webp' },
        { name: 'New Perlo', meta: 'FR · 3 avis', title: 'Tellement rentable', avatar: 'ms-av-perlo.webp' },
        { name: 'El Poupoucoincoin', meta: 'RE · 1 avis', avatar: 'ms-av-poupou.webp' },
        { name: 'Simon', meta: 'FR · 2 avis', title: '10/10', avatar: 'ms-av-simon.webp' },
        { name: 'XOON', meta: 'FR · 1 avis', title: 'Meilleur accompagnement pour devenir…', text: 'Meilleur accompagnement pour devenir créateur de contenu !', initials: 'XO', bg: '#FFF1BF', fg: '#3D3A30' },
        { name: 'Phyress', meta: 'FR · 1 avis', title: 'MS est juste INCROYABLE !!!', initials: 'P', bg: '#C2185B', fg: '#fff' },
      ],
      bottom: [
        { name: 'Alexandre', meta: 'FR · 1 avis', title: 'Une pure merveille', text: 'Une pure merveille, merci à toute l’équipe de MS', initials: 'A', bg: '#E8436F', fg: '#fff' },
        { name: 'DELTAx', meta: 'FR · 1 avis', title: 'Incroyable', initials: 'DE', bg: '#FCE4EC', fg: '#3D3A30' },
        { name: 'JaimeLeChocolat', meta: 'DZ · 1 avis', title: 'ACHETEZ ATTENDER PLUS', initials: 'J', bg: '#6A1B9A', fg: '#fff' },
        { name: 'Pierre', meta: 'FR · 1 avis', title: 'Très instructif', initials: 'PI', bg: '#FCE4EC', fg: '#3D3A30' },
        { name: 'Thomas', meta: 'CA · 1 avis', title: 'Grandir ensemble', initials: 'TH', bg: '#FFF1BF', fg: '#3D3A30' },
        { name: 'Cyprien Rajau', meta: '1 avis · FR', title: 'Absolute banger !!!', avatar: 'ms-av-cyprien.webp' },
      ],
    },
    speakersTitle: 'Sur MS : des conférenciers exceptionnels !',
    speakers: Array.from({ length: 10 }, (_, i) => `ms-speaker${String(i + 1).padStart(2, '0')}.webp`),
    tiersTitle: 'Et toi, quel clippeur deviendras-tu ?',
    band: '1 M DE VUES = 1 MOIS DE MS',
    alone: { title: 'Seul', text: 'Des clips postés pour rien : pas de récompense, pas de suivi, personne pour t’aider…' },
    withUs: { title: 'Avec Loann', lines: ['Tes vues paient.', 'Des mois de MS offerts', 'Un classement chaque semaine', 'Un Discord pour t’aider', 'Une commu de clippeurs'] },
    faqAside: 'Tu as encore des questions ? Pose-les sur le Discord !',
  },
  statuses: { pending: 'En attente', delivered: 'Livré ✅', refunded: 'Remboursé' },
  texts: {
    heroTitle: '**1 M de vues** = 1 mois de MS',
    heroText: 'Poste des clips de Loann sur TikTok, Instagram ou YouTube. Chaque vue te rapporte des coins, que tu échanges contre des mois de Merguez Superstar, sa formation YouTube.',
    ticker: ['CLIPPE LOANN', 'FAIS DES VUES', 'GAGNE MERGUEZ SUPERSTAR', '1M DE VUES = 1 MOIS', 'PERCE SUR YOUTUBE'],
    heroCta: 'Voir ma progression',
    steps: [
      { title: 'Crée ton clip', text: 'Un passage de Loann qui mérite d’être vu.' },
      { title: 'Poste-le', text: 'Sur TikTok, Instagram ou YouTube.' },
      { title: 'Gagne des coins', text: '10 coins pour 1 000 vues, tous comptes confondus.' },
      { title: 'Prends ton mois', text: '10 000 coins = 1 mois de Merguez Superstar.' },
    ],
    shopTitle: 'Récompenses',
    shopText: 'Échange tes coins contre des mois de Merguez Superstar, la formation YouTube de Loann.',
    clipTitle: 'Clipper',
    clipText: 'Poste des clips de Loann sur TikTok, Instagram ou YouTube. Tes vues sont comptées toutes les 1 à 2 nuits.',
    rankingText: 'Les clippeurs qui ont fait le plus de vues ces 7 derniers jours.',
    footer: 'Loann Clipping',
    deliveredDm: '✅ Ton **{item}** a été ajouté sur ton compte !',
    dmFooter: 'Loann Clipping · Clippe, gagne Merguez Superstar',
    faq: [
      { q: 'Comment je gagne des coins ?', a: 'Tu postes des clips de Loann sur TikTok, Instagram ou YouTube. Chaque vue compte : 1 000 vues = 10 coins, tous comptes confondus.' },
      { q: 'Comment je relie mes comptes ?', a: 'Sur le Discord, clique sur « S’inscrire » dans le salon inscription et renseigne tes comptes.' },
      { q: 'Quand mes vues sont-elles comptées ?', a: 'Une fois par jour. Tous tes clips postés depuis le 1er août 2026 comptent, même ceux d’avant ton inscription.' },
      { q: 'Comment je reçois mon mois de Merguez Superstar ?', a: 'Renseigne l’e-mail de ton compte Merguez Superstar dans ton profil, échange 10 000 coins dans la boutique : ton accès est envoyé sur cet e-mail et tu reçois un message Discord dès que c’est fait.' },
      { q: 'Il faut combien d’abonnés ?', a: 'Aucun minimum. Un compte qui vient de démarrer peut gagner des coins dès son premier clip.' },
    ],
    finalTitle: 'Prêt à **clipper** ?',
    finalText: 'Connecte-toi avec Discord, relie tes comptes et commence à gagner des coins dès ton prochain clip.',
  },
};
