import type { CreatorConfig } from './types.js';

/** SQUIDUU : site sobre et sombre (gabarit « sober »), récompense = 1 mois de Squiduuverse. */
export const squiduu: CreatorConfig = {
  id: 'squiduu',
  programName: 'SQUIDUU',
  creatorName: 'SQUIDUU',
  youtube: 'SQUIDUU',
  theme: 'sober',
  // Charte du squiduuverse (squiduuverse.com) : noir #0B0A0C, cartes #17161A, jaune #FCD005, Montserrat
  colors: { bg: '#0B0A0C', card: '#17161A', border: '#2A2930', text: '#F5F5F7', muted: '#9B9AA3', accent: '#FCD005', accentInk: '#0B0A0C' },
  font: 'Montserrat',
  logoText: 'squiduu.',
  pointsPer1000: 10,
  rewardAccount: {
    kind: 'email',
    title: 'Compte Squiduuverse',
    label: 'E-mail utilisé sur le Squiduuverse',
    placeholder: 'ton@email.com',
    badge: 'Compte Squiduuverse relié',
    deliveryHint: 'Le mois est ajouté au compte Squiduuverse lié à cet e-mail.',
  },
  reward: {
    name: '1 mois de Squiduuverse',
    description: 'Un mois d’accès au Squiduuverse. Tu peux en échanger autant que tu veux : les mois s’additionnent.',
    price: 10_000,
    ref: 'squiduuverse-1m',
    url: 'https://squiduuverse.com/',
    linkLabel: 'Découvrir le Squiduuverse',
  },
  discord: {
    welcome: [
      '👋 **Salut et bienvenue sur Squiduu Clipping !**',
      '',
      'Ici, tu peux gagner **gratuitement des mois de Squiduuverse** grâce à tes clips de {creator} 🎮',
      '',
      '🎁 **Comment gagner des récompenses ?**',
      'C’est très simple : tu fais des clips des vidéos de {creator} 👀',
      '',
      '📱 Crée tes propres comptes **YouTube, TikTok et Instagram**, puis poste tes clips dessus.',
      '✨ Les vues de YouTube + TikTok + Instagram sont **toutes comptées ensemble** !',
      '🪙 **1 000 vues = {rate} coins**, et **10 000 coins = 1 mois de Squiduuverse**.',
      '',
      '😕 **Tu ne sais pas faire de montage ?**',
      'Pas de panique, c’est normal quand on débute 😊 Pose tes questions dans ❓│aide : on t’explique tout, étape par étape.',
      '',
      '🚀 **Prêt à commencer l’aventure ?**',
      'Clique sur **➡️ Continuer** juste en dessous pour découvrir les règles et le déroulement 👇',
    ].join('\n'),
    rules: [
      '🎮 Bienvenue sur le serveur officiel de clipping de {creator} !',
      'Le but est simple : créer des clips de ses vidéos et les poster sur tes comptes. 🎥',
      'Merci de respecter ces quelques règles pour garder un serveur propre et agréable 👇',
      '',
      '**1️⃣・Respect** 🤝',
      'Respecte les autres membres. ❌ Pas d’insultes, de moqueries ou de harcèlement. 🗣️ Les désaccords se règlent calmement.',
      '',
      '**2️⃣・Clips** 🎥',
      '✂️ Les clips doivent venir des vidéos de {creator}. 🔥 Les moments drôles, impressionnants ou insolites sont les bienvenus !',
      '',
      '**3️⃣・Pas de triche** 🚫',
      '❌ Pas de faux clips, de faux comptes ni de vues achetées. ⚠️ Les coins gagnés en trichant sont retirés.',
      '',
      '**4️⃣・Un compte = une personne** 🔗',
      'Un compte TikTok, YouTube ou Instagram ne peut être relié qu’à un seul clippeur.',
      '',
      '**5️⃣・Pas de spam ni de pub** 📢',
      '🚫 Pas de messages en boucle ni de mentions inutiles. ❌ Pas de pub pour d’autres serveurs, chaînes ou comptes sans l’accord du staff.',
      '',
      '**6️⃣・Sécurité** 🛡️',
      '🔒 Ne partage jamais tes infos perso (📍 adresse, 📱 numéro, 🔑 mot de passe, 🏫 école) et ne les demande pas aux autres.',
      '',
      '**7️⃣・Staff** 👮',
      '🛡️ Respecte les décisions du staff. 📩 Un problème ? Écris dans ❓│aide plutôt que de lancer une dispute.',
      '',
      '━━━━━━━━━━━━━━━━━━',
      '🎬 **Objectif : faire découvrir {creator} au plus de monde possible !**',
      '✂️ CLIP • POSTE • GAGNE 🪙',
      '',
      '⚠️ Le non-respect des règles peut entraîner un avertissement, un mute ou un bannissement.',
    ].join('\n'),
  },
  levels: [
    { name: 'Débutant', emoji: '🌱', min: 0 },
    { name: 'Confirmé', emoji: '⚡', min: 10_000 },
    { name: 'Pro', emoji: '🔥', min: 100_000 },
    { name: 'Élite', emoji: '💎', min: 1_000_000 },
  ],
  statuses: { pending: 'En attente', delivered: 'Livrée', refunded: 'Remboursée' },
  texts: {
    heroTitle: 'Clippe SQUIDUU. **Gagne des coins.**',
    heroText: 'Poste des clips de SQUIDUU sur TikTok, Instagram ou YouTube. Chaque vue te rapporte des coins, que tu échanges ensuite dans la boutique.',
    heroCta: 'Commencer à clipper',
    steps: [
      { title: 'Crée ton clip', text: 'Un passage de SQUIDUU qui mérite d’être vu.' },
      { title: 'Poste-le', text: 'Sur TikTok, Instagram ou YouTube.' },
      { title: 'Gagne des coins', text: '10 coins pour 1 000 vues, tous comptes confondus.' },
      { title: 'Échange-les', text: 'Dans la boutique, quand tu as assez de coins.' },
    ],
    shopTitle: 'Récompenses',
    shopText: 'Échange tes coins dans la boutique.',
    clipTitle: 'Clipper',
    clipText: 'Poste des clips de SQUIDUU sur TikTok, Instagram ou YouTube. Tes vues sont comptées une fois par jour.',
    rankingText: 'Les clippeurs qui ont fait le plus de vues ces 7 derniers jours.',
    footer: 'SQUIDUU',
    deliveredDm: '✅ Ton échange **{item}** a été livré.',
    dmFooter: 'SQUIDUU · Clippe, gagne des coins',
    faq: [
      { q: 'Comment je gagne des coins ?', a: 'Tu postes des clips de SQUIDUU sur TikTok, Instagram ou YouTube. Chaque vue compte : 1 000 vues = 10 coins, tous comptes confondus.' },
      { q: 'Comment je relie mes comptes ?', a: 'Sur le Discord, ouvre un ticket et fais /inscription. Tu renseignes tes comptes et ton e-mail Squiduuverse, c’est tout.' },
      { q: 'Quand mes vues sont-elles comptées ?', a: 'Une fois par jour. Seules les vues faites après ton inscription rapportent des coins.' },
      { q: 'Il faut combien d’abonnés ?', a: 'Aucun minimum. Un compte qui vient de démarrer peut gagner des coins dès son premier clip.' },
    ],
    finalTitle: 'Prêt à **clipper** ?',
    finalText: 'Connecte-toi avec Discord, relie tes comptes et commence à gagner des coins dès ton prochain clip.',
  },
};
